### PR TITLE
fix: many inconsistencies

### LINKED ISSUE #40: 'TypeError: updater is not a function' thrown when updating a lexical binding.
Setting the prototype of namespaces should be disallowed. 

**Steps to reproduce**

In `make-importer`, replace `moddir/index.js` with:
```js
export let foo = 111;
export { foo as bar } from './index.js';
```

Then execute:
```sh
$ node -r esm test/test-moddir.js 
TAP version 13
# moddir index.js
not ok 1 unexpected exception
  ---
    operator: notEqual
    expected: |-
      [TypeError: updater is not a function]
    actual: |-
      [TypeError: updater is not a function]
```

Expected result: no error. 
```
$ node -r esm test/moddir/index.js
// no error
```

### LINKED ISSUE #53: 'TypeError: updater is not a function' thrown when updating a lexical binding.
Setting the prototype of namespaces should be disallowed. 

**Steps to reproduce**

In `make-importer`, replace `moddir/index.js` with:
```js
export let foo = 111;
export { foo as bar } from './index.js';
```

Then execute:
```sh
$ node -r esm test/test-moddir.js 
TAP version 13
# moddir index.js
not ok 1 unexpected exception
  ---
    operator: notEqual
    expected: |-
      [TypeError: updater is not a function]
    actual: |-
      [TypeError: updater is not a function]
```

Expected result: no error. 
```
$ node -r esm test/moddir/index.js
// no error
```

### LINKED ISSUE #57: 'TypeError: updater is not a function' with mulptiple let or const exports.
When exporting the same `let`, or `const` declaration under different name, the system throws 'TypeError: updater is not a function'.

**Steps to reproduce**
In `make-importer`, replace `moddir/index.js` with:
```js
export let local1 = 23;
export { local1 as indirect } from './index.js';
```

Then execute:
```sh
$ node -r esm test/test-moddir.js 
```
Actual result:
```
$ node  -r esm test/test-moddir.js 
TAP version 13
# moddir index.js
not ok 1 unexpected exception
  ---
    operator: notEqual
    expected: |-
      [TypeError: updater is not a function]
    actual: |-
      [TypeError: updater is not a function]
    at: Test._387‍.r.test (~/projects/make-importer/test/test-moddir.js:61:7)
    stack: |-
      TypeError: updater is not a function
          at Object.init [as local1] (~/projects/make-importer/src/moduleInstance.js:73:13)
          at eval (eval at <anonymous> (eval at <anonymous> (~/projects/make-importer/test/test-moddir.js:14:18)), <anonymous>:3:26)
 ```
Expected result, same as node's native import:
```sh
$ node -r esm test/moddir/index.js
// no error
```

### LINKED ISSUE #60: 'RangeError: Maximum call stack size exceeded' with mulptiple var, function, or class exports.
When exporting the same `var`, `function` or `class` under different name, the system throws 'RangeError: Maximum call stack size exceeded'.

**Steps to reproduce**
In `make-importer`, replace `moddir/index.js` with:
```js
export var local1 = null;
export { local1 as indirect } from './index.js';
```
Then execute:
```sh
$ node -r esm test/test-moddir.js 
```
Actual result:
```
$ node  -r esm test/test-moddir.js 
TAP version 13
# moddir index.js
not ok 1 unexpected exception
  ---
    operator: notEqual
    expected: |-
      [RangeError: Maximum call stack size exceeded]
    actual: |-
      [RangeError: Maximum call stack size exceeded]
    at: Test._387‍.r.test (~/projects/make-importer/test/test-moddir.js:61:7)
    stack: |-
      RangeError: Maximum call stack size exceeded
          at Array Iterator.next (<anonymous>)
          at update (~/projects/make-importer/src/moduleInstance.js:139:22)
          at update (~/projects/make-importer/src/moduleInstance.js:140:13)
          at update (~/projects/make-importer/src/moduleInstance.js:140:13)
          at update (~/projects/make-importer/src/moduleInstance.js:140:13)
          at update (~/projects/make-importer/src/moduleInstance.js:140:13)
          at update (~/projects/make-importer/src/moduleInstance.js:140:13)
          at update (~/projects/make-importer/src/moduleInstance.js:140:13)
          at update (~/projects/make-importer/src/moduleInstance.js:140:13)
          at update (~/projects/make-importer/src/moduleInstance.js:140:13)
```
Expected result, same as node's native import:
```sh
$ node -r esm test/moddir/index.js
// no error
```

### LINKED ISSUE #61: Namespace properties are not sorted
**Steps to reproduce 2**
In `make-importer`, replace `moddir/index.js` with:
```js
const sameValue = (actual, expected, msg) => { 
  console.log(msg, actual === expected);
}

var x;

export { x as Z };
export { x as a };
export { x as A };
export { x as aa };
export { x as λ }; // u03bb
export { x as _ };
export { x as $$ };
export { x as $ };
export default null;

import * as ns from './index.js';

var names = Object.getOwnPropertyNames(ns);

sameValue(names.length, 9, 'count of names');
sameValue(names[0], '$', 'names[0] === "$"');
sameValue(names[1], '$$', 'names[1] === "$$"');
sameValue(names[2], 'A', 'names[2] === "A"');
sameValue(names[3], 'Z', 'names[3] === "Z"');
sameValue(names[4], '_', 'names[4] === "_"');
sameValue(names[5], 'a', 'names[5] === "a"');
sameValue(names[6], 'aa', 'names[6] === "aa"');
sameValue(names[7], 'default', 'names[7] === "default"');
sameValue(names[8], '\u03bb', 'names[8] === "\u03bb"');
```
Then execute:
```sh
$ node -r esm test/test-moddir.js 
```
Actual result:
```
count of names true
names[0] === "$" false
names[1] === "$$" false
names[2] === "A" false
names[3] === "Z" false
names[4] === "_" false
names[5] === "a" false
names[6] === "aa" false
names[7] === "default" false
names[8] === "λ" false
```
Expected result: same as node's native import:
```sh
$ node -r esm test/moddir/index.js
count of names true
names[0] === "$" true
names[1] === "$$" true
names[2] === "A" true
names[3] === "Z" true
names[4] === "_" true
names[5] === "a" true
names[6] === "aa" true
names[7] === "default" true
names[8] === "λ" true
```

### LINKED ISSUE #76: Ambiguous exports are present in imports
Ambiguous exports are not reflected in module namespace objects, nor do they trigger an error upon resolution.

**Steps to reproduce**
In `make-importer`, replace `moddir/index.js` with:
```js
import * as ns from './foo.js';
if ('both' in ns) { throw 'Ambiguous export is present' };
console.log('Ambiguous export is not present');
```
Replace `moddir/foo.js` with:
```js
export * from './mod1.js';
export * from './mod2.js';
```
Replace `moddir/mod1.js` with:
```js
export var both = null;
```
Replace `moddir/mod2.js` with:
```js
export var both = null;
```

Then execute:
```sh
$ node -r esm test/test-moddir.js 
```
Actual result:
```
$ node  -r esm test/test-moddir.js 
TAP version 13
# moddir index.js
not ok 1 unexpected exception
  ---
    operator: notEqual
    expected: 'Ambiguous export is present'
    actual:   'Ambiguous export is present'
```
Expected result, same as node's native import:
```
$ node -r esm test/moddir/index.js
Ambiguous export is not present
```

### PR DESCRIPTION
**Pull request by michaelfig**
Closes: #24 namespace not sorted
Closes: #25 circular references infinite recursion
Closes: #28 ambiguous exports
Closes: #30 and closes #40 updater is not a function

### CODE REVIEW

File: src/moduleInstance.js [hunk 1]
```diff
@@ -222,36 +233,42 @@ export function makeModuleInstance(
...
+            return value;
+          },
+          set: undefined,
+          enumerable: true,
+          configurable: false,
+        };
+      }
     }
+
+    // Sort the module namespace.  Some es262 tests rely on this behaviour.
```
Comment (jfparadis) [inline src/moduleInstance.js]: Maybe we should say "as per specifications" since we're not fixing to pass the test, but to conform to specifications and avoid runtime failures modules relying to that behavior.

**Review by jfparadis — APPROVED** [review]
