### PR TITLE
fix(allowHidden): set this flag to allow the functor to run

### LINKED ISSUE #37: 'SyntaxError: unknown: The $h‍_imports identifier is reserved' when using dynamic imports
**Steps to reproduce**

In `make-importer`, replace `moddir/index.js` with:
```js
import('./index');
export var local1;
```
And replace `test-moddir.js` with:
```js
/* eslint-disable import/no-extraneous-dependencies */
import { test } from 'tape-promise/tape';
import { makeEvaluators } from '@agoric/evaluate';

import makeModuleTransformer from '@agoric/transform-module';
import * as babelCore from '@babel/core';
import fs from 'fs';
import path from 'path';

import makeImporter, * as mi from '../src';

const readFile = ({ pathname }) => fs.promises.readFile(pathname, 'utf-8');

const protoHandlers = new Map([['file', readFile]]);

test('moddir index.js', async t => {
  const rootUrl = `file://${path.join(__dirname, 'moddir')}`;

  const transforms = [];
  const { evaluateProgram } = makeEvaluators({ transforms });
  const importer = makeImporter({
    resolve: mi.makeRootedResolver(rootUrl),
    locate: mi.makeSuffixLocator('.js'),
    retrieve: mi.makeProtocolRetriever(protoHandlers),
    rewrite: mi.makeTransformRewriter(transforms),
    rootLinker: mi.makeEvaluateLinker(evaluateProgram),
  });
  transforms[0] = makeModuleTransformer(babelCore, importer);

  try {
    await importer({ spec: '.', url: `${rootUrl}/` }, {});
  } catch (e) {
    t.isNot(e, e, 'unexpected exception');
  } finally {
    t.end();
  }
});
```

Then execute:
```sh
 node -r esm test/test-moddir.js 
TAP version 13
# moddir index.js
not ok 1 unexpected exception
  ---
    operator: notEqual
    expected: |-
      { [SyntaxError: unknown: The $h‍_imports identifier is reserved
```

Expected result: no error.
```
$ node -r esm test/moddir/index.js
// no error
```

### LINKED ISSUE #51: 'SyntaxError: unknown: The $h‍_imports identifier is reserved' when using dynamic imports
**Steps to reproduce**

In `make-importer`, replace `moddir/index.js` with:
```js
import('./index');
export var local1;
```
And replace `test-moddir.js` with:
```js
/* eslint-disable import/no-extraneous-dependencies */
import { test } from 'tape-promise/tape';
import { makeEvaluators } from '@agoric/evaluate';

import makeModuleTransformer from '@agoric/transform-module';
import * as babelCore from '@babel/core';
import fs from 'fs';
import path from 'path';

import makeImporter, * as mi from '../src';

const readFile = ({ pathname }) => fs.promises.readFile(pathname, 'utf-8');

const protoHandlers = new Map([['file', readFile]]);

test('moddir index.js', async t => {
  const rootUrl = `file://${path.join(__dirname, 'moddir')}`;

  const transforms = [];
  const { evaluateProgram } = makeEvaluators({ transforms });
  const importer = makeImporter({
    resolve: mi.makeRootedResolver(rootUrl),
    locate: mi.makeSuffixLocator('.js'),
    retrieve: mi.makeProtocolRetriever(protoHandlers),
    rewrite: mi.makeTransformRewriter(transforms),
    rootLinker: mi.makeEvaluateLinker(evaluateProgram),
  });
  transforms[0] = makeModuleTransformer(babelCore, importer);

  try {
    await importer({ spec: '.', url: `${rootUrl}/` }, {});
  } catch (e) {
    t.isNot(e, e, 'unexpected exception');
  } finally {
    t.end();
  }
});
```

Then execute:
```sh
 node -r esm test/test-moddir.js 
TAP version 13
# moddir index.js
not ok 1 unexpected exception
  ---
    operator: notEqual
    expected: |-
      { [SyntaxError: unknown: The $h‍_imports identifier is reserved
```

Expected result: no error.
```
$ node -r esm test/moddir/index.js
// no error
```

### PR DESCRIPTION
**Pull request by michaelfig**
I'm willing to entertain other ways of fixing this, but given the already-tight coupling between make-importer and transform-module, this may be the best way.

Closes #37

### CODE REVIEW

File: src/link.js [hunk 1]
```diff
@@ -5,6 +5,11 @@ const { keys } = Object;
 const makeMap = (...args) => new Map(...args);
 
 export const makeEvaluateLinker = (evaluator, instanceCache = new Map()) => {
+  const tolerantEvaluator = (src, endowments, options = {}) => {
+    // Our sources have been already rewritten, so allow the hidden identifiers.
+    options.allowHidden = true;
```
Comment (jfparadis) [inline src/link.js]: Should probably clone the options first to avoid side effect on function arguments.
```js
options = { ...options, allowHidden: true };
```
